Issue#33 newly registered users can't edit their profile
UCL-INGI/ictm-teaching pull request #39
Opened 2024-10-01 19:17 UTC by SamuelVch98

2024-10-11 11:31 UTC, anthonygego requested changes

2024-10-11 11:31 UTC, anthonygego commented on user.py
> +@check_access_level(Role.USER)
There is no need to define such a role. You can simply allow any logged user and remove this decorator.

2024-10-11 11:31 UTC, anthonygego commented on db.py
> +            Role.USER: True,
You can therefore remove this one and let `False` be the default value. Changing this to a dictionary lookup remains a good idea.

2024-10-14 14:06 UTC, AlexandreDoneux commented on db.py
> +    USER = "user"
Remove this line, not needed anymore

2024-10-14 14:06 UTC, AlexandreDoneux commented on db.py
> +            Role.ADMIN: self.admin,
Keep consistency in your variable names : use `self.is_admin`

2024-10-15 07:49 UTC, anthonygego commented on db.py
> +    USER = "user"
```suggestion

```

2024-10-15 07:49 UTC, anthonygego commented on user.py
> +@check_access_level(Role.USER)
```suggestion
```

2024-10-15 07:55 UTC, anthonygego commented
https://github.com/UCL-INGI/ictm-teaching/blob/22afecd73629950459edeadc240ca6b4c2c87bcf/user.py#L134-L136
also need to be adapted.

2024-10-15 14:00 UTC, anthonygego approved these changes

2024-10-15 14:00 UTC, merged